[default]

####################################################
############### ここから先はシステム設定 #############
####################################################
# ----- ログレベル -----
log_level = debug

# ----- exeモード -----
exe_mode = False

# ----- 処理間隔時間(秒) -----
sleep_time = 3
sleep_time_for_comfirm = 20

# ----- イテレーション回数 -----
iter_count = 4

# ----- デバッグモード立ち上げコマンド -----
debug_mode_command      = "C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --user-data-dir=C:\selenium\chrome-profile
debug_mode_url          = localhost:9222


# ----- Chrome Driverパス -----
chromedriver_path       = c:\chromedriver-win64\chromedriver.exe


# ----- OpenAI モデル -----
# openai_model = gpt-4.1-mini
openai_model = gpt-5-mini

# ----- SmartDB URL -----
base_url = https://duskinssc.smartdb.jp/


# ----- ダウンロードフォルダ -----
download_dir = C:\Users\ogiki\Downloads
# download_dir = C:\Users\Ryusuke_Kimura\Downloads
